### ISSUE TITLE
TypeError: Cannot set property 'isAMP' of undefined

### ISSUE THREAD

**Issue by bluedge** [jlopezxs/express-amp#1]
Running the example trigger the following error (applying the module to your own express site triggers the same error)
TypeError: Cannot set property 'isAMP' of undefined
Note: renderOpts seems to be undefined

**Comment by jlopezxs** [comment]
Hey, @bluedge .
Thanks for the report!
I merge you PR #2 to fix that. And in a few hours I will publish a new release.
